spring:
  datasource:
    url:
    username: user
    password: user

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/Toma

  kafka:
    bootstrap-servers:
    consumer:
      group-id: order-group-test
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

server:
  port: 0

grpc:
  client:
    storage-service:
      address: static://localhost:9090
      negotiation-type: plaintext
      deadline-after: 5s